version: '3'
services:
    frontend:
      build: frontend
      environment:
        - NODE_ENV=production
        - PGHOST=database
        - PGUSER=root
        - PGPASSWORD=example
        - PGDATABASE=covid
        - PGPORT=5432
      volumes:
        - ./frontend:/home/node/app
      ports:
        - 8081:3000
      restart: always
    backend:
      build: backend
      environment:
        - NODE_ENV=production
        - PGHOST=database
        - PGUSER=root
        - PGPASSWORD=example
        - PGDATABASE=covid
        - PGPORT=5432
      volumes:
        - ./backend:/home/node/app
      ports:
        - 8082:3000
      # restart: always
    database:
      build:
        context: ./
        dockerfile: ./database/Dockerfile
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: example
        POSTGRES_DB: covid
      volumes:
        - ./data/db/postgres:/var/lib/postgresql/data
      ports:
        - 5432:5432
      restart: always

    mapserver:
      image: klokantech/openmaptiles-server:1.10
      ports:
        - 8080:80
      volumes:
        - ./data/map:/data