version: '3'
services:
    webserver:
      image: node:14
      environment:
        - NODE_ENV=production
      volumes:
        - ./app:/home/node/app
      ports:
        - 8081:3000
      command: "npm run dev"
      user: node
      working_dir: /home/node/app
      
    database:
      image: mongo:3.6
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      volumes:
            - ./data/db/mongo:/data/db

    mapserver:
      image: klokantech/openmaptiles-server:1.10
      ports:
        - 8080:80
      volumes:
        - ./data/map:/data