version: '3'
services:
    webserver:
      build: app
      environment:
        - NODE_ENV=production
      volumes:
        - ./app:/home/node/app
      ports:
        - 8081:3000
      
    database:
      image: postgres
      environment:
        POSTGRES_USERNAME: root
        POSTGRES_PASSWORD: example
      volumes:
            - ./data/db/postgres:/data/db
      ports:
        - 5432:5432

    mapserver:
      image: klokantech/openmaptiles-server:1.10
      ports:
        - 8080:80
      volumes:
        - ./data/map:/data
