version: '3'
services:
    nodejs:
      image: node:14
      environment:
        - NODE_ENV=production
      volumes:
        - ./app:/home/node/app
      ports:
        - 8080:8080
      command: "npm start"
      user: node
      working_dir: /home/node/app
      
    mysql:
      image: mysql:8
      environment:
        - MYSQL_DATABASE=db
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
      volumes:
            - ./data/db/mysql:/var/lib/mysql
      user: mysql